name: project_ecommerce_shoes_flutter_2025
description: "تطبيق متجر إلكتروني لبيع الأحذية باستخدام Flutter"

# لمنع النشر العرضي على pub.dev
publish_to: 'none'




version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.5 # لإدارة الحالة والتنقل
  flutter_svg: ^2.0.7 # لعرض صور SVG
  cached_network_image: ^3.3.0 # لإدارة صور الشبكة
  url_launcher: ^6.1.7
  intl: ^0.18.0
  http: ^1.5.0
  iconsax: ^0.0.8
  smooth_page_indicator: ^1.2.1
  flutter_native_splash: ^2.3.1
  carousel_slider: ^5.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

#flutter_native_splash:
#  color: "#ffffff"
#  android: true
#  ios: true
#  android_12:
#    color: "#ffffff"